Style/fixes
oSoc20/ArTIFFact-Control pull request #108
Opened 2020-07-28 14:38 UTC by TimPensart

2020-07-28 15:05 UTC, FreekDS requested changes
Can you also take a look at the continue button when creating a configuration? 🌝

2020-07-29 07:28 UTC, BramDC3 approved these changes

2020-07-29 09:21 UTC, FreekDS approved these changes

2020-07-29 09:22 UTC, AmberPerard approved these changes

2020-07-29 09:22 UTC, merged